[(kwd_spec)
 (kwd_inv)
 (kwd_au)
 (kwd_atomic)
 (kwd_axiom)
 (kwd_atomic_token)
 (kwd_auto)
 (kwd_cas)
 (kwd_case)
 (kwd_data)
 (kwd_else)
 (kwd_ensures)
 (kwd_const)
 (kwd_field)
 (kwd_func)
 (kwd_ghost)
 (kwd_havoc)
 (kwd_if)
 (kwd_include)
 (kwd_module)
 (kwd_invariant)
 (kwd_import)
 (kwd_implicit)
 (kwd_lemma)
 (kwd_rep)
 (kwd_new)
 (kwd_perm)
 (kwd_proc)
 (kwd_requires)
 (kwd_return)
 (kwd_returns)
 (kwd_type)
 (kwd_var)
 (kwd_with)
 (kwd_while)
 (kwd_quantifier)] @keyword
[(op_implies) (op_iff) (op_eq) (op_eqeq) (op_neq) (op_leq) (op_geq)
      (op_lt) (op_gt) (op_or) (op_and) (op_subseteq) (op_in) (op_not_in)
      (op_not) (op_plus) (op_minus) (op_div) (op_mul) (op_coloneq)
      (op_coloncolon) (op_dot) (op_qmark) (op_colonpipe)] @operator
(number) @number
(type_expr) @type
[ (block_comment)
  (comment_text)
  (comment) ] @comment
[
  (delim_lbracepipe)
  (delim_rbracepipe)
  (delim_lbracketpipe)
  (delim_rbracketpipe)
  (delim_lparen)
  (delim_rparen)
  (delim_lbrace)
  (delim_rbrace)
  (delim_lbracket)
  (delim_rbracket)
  (delim_lghostbrace)
  (delim_rghostbrace)
] @punctuation.bracket

[
  (kwd_own) (kwd_const)
] @constant.builtin

(string) @string
